export const ENGLISH_SENTENCE_TEMPLATES: Record<string, string> = {
  // Fruits & Vegetables
  apple: "I eat a red apple",
  banana: "The banana is yellow and sweet",
  grapes: "I love purple grapes",
  strawberry: "The strawberry is red and juicy",
  carrot: "The carrot is crunchy and orange",
  cucumber: "The cucumber is cool and green",
  watermelon: "The watermelon is big and juicy",
  broccoli: "I eat healthy broccoli",
  orange: "The orange is round and juicy",
  lemon: "The lemon is sour and yellow",
  peach: "The peach is soft and sweet",
  cherry: "The cherry is small and red",
  kiwi: "The kiwi is fuzzy and green",

  // Counting (1-15)
  "1": "One",
  "2": "Two",
  "3": "Three",
  "4": "Four",
  "5": "Five",
  "6": "Six",
  "7": "Seven",
  "8": "Eight",
  "9": "Nine",
  "10": "Ten",
  "11": "Eleven",
  "12": "Twelve",
  "13": "Thirteen",
  "14": "Fourteen",
  "15": "Fifteen",

  // Shapes & Colors
  circle: "The circle is round",
  square: "The square has four sides",
  diamond: "The diamond is shiny",
  triangle: "The triangle has three sides",
  star: "The star shines bright",
  oval: "The oval is like an egg",
  rectangle: "The rectangle is long",
  pentagon: "The pentagon has five sides",
  hexagon: "The hexagon has six sides",
  blue: "The sky is blue",
  red: "The apple is red",
  // Note: 'orange' color uses the fruit definition from above
  green: "The grass is green",
  purple: "The grapes are purple",
  white: "The snow is white",
  black: "The night is black",
  brown: "The tree is brown",
  pink: "The flower is pink",
  yellow: "The sun is yellow",

  // Animals & Nature
  dog: "The dog says woof",
  cat: "The cat says meow",
  fox: "The fox is clever",
  turtle: "The turtle moves slowly",
  butterfly: "The butterfly is beautiful",
  owl: "The owl says hoot",
  ant: "The ant is small and strong",
  duck: "The duck says quack",
  elephant: "The elephant is big",
  fish: "The fish swims in water",
  giraffe: "The giraffe has a long neck",
  penguin: "The penguin waddles on ice",

  // Things That Go
  car: "The car drives on the road",
  bus: "The yellow bus takes us to school",
  "fire truck": "The fire truck has a loud siren",
  airplane: "The airplane flies in the sky",
  rocket: "The rocket goes to space",
  bicycle: "I ride my bicycle to the park",
  helicopter: "The helicopter goes up and down",
  boat: "The boat floats on the water",
  train: "The train goes on the tracks",
  taxi: "The taxi takes people places",
  van: "The van carries our family",
  scooter: "I ride my scooter fast",
  motorcycle: "The motorcycle goes zoom",

  // Weather Wonders
  sunny: "It is sunny today",
  cloudy: "The sky is cloudy",
  rainy: "It is rainy outside",
  stormy: "The weather is stormy",
  snowy: "It is snowy and cold",
  rainbow: "I see a beautiful rainbow",
  tornado: "The tornado spins around",
  windy: "It is very windy today",
  moon: "The moon shines at night",
  sun: "The sun gives us light",
  foggy: "The morning is foggy",
  lightning: "The lightning flashes bright",

  // Feelings & Actions
  happy: "I feel happy and smile",
  sad: "When I am sad I might cry",
  angry: "Take a breath when you feel angry",
  sleepy: "I am sleepy and yawn",
  hug: "Give me a big hug",
  clap: "Clap your hands together",
  dance: "Let's dance to the music",
  flip: "Watch me flip and spin",
  smile: "I smile when I am happy",
  laugh: "I laugh at funny jokes",
  think: "I think before I speak",
  celebrate: "Let's celebrate together",
  wave: "I wave hello to my friends",

  // Body Parts
  eye: "I see with my eyes",
  ear: "I hear with my ears",
  nose: "I smell with my nose",
  mouth: "I talk with my mouth",
  tongue: "My tongue tastes food",
  hand: "I wave my hand hello",
  foot: "I walk with my feet",
  leg: "I jump with my legs",
  tooth: "I brush my teeth",
  arm: "I swing my arms",
  brain: "My brain helps me think",
  heart: "My heart beats in my chest",

  // Alphabet (letters A-Z)
  a: "A is for Apple",
  b: "B is for Ball",
  c: "C is for Cat",
  d: "D is for Dog",
  e: "E is for Elephant",
  f: "F is for Fish",
  g: "G is for Giraffe",
  h: "H is for House",
  i: "I is for Ice cream",
  j: "J is for Juice",
  k: "K is for Kite",
  l: "L is for Lion",
  m: "M is for Moon",
  n: "N is for Nest",
  o: "O is for Orange",
  p: "P is for Penguin",
  q: "Q is for Queen",
  r: "R is for Rainbow",
  s: "S is for Star",
  t: "T is for Tree",
  u: "U is for Umbrella",
  v: "V is for Van",
  w: "W is for Watermelon",
  x: "X is for X-ray",
  y: "Y is for Yellow",
  z: "Z is for Zebra",
};
