export const FRENCH_GAMEPLAY_COMPLETION_TEMPLATES: Record<string, string> = {
  white: "Le nuage est blanc",
  brown: "L'ours est brun",
  black: "Le ciel est noir la nuit",
  diamond: "Le losange a quatre côtés",
  owl: "Le hibou hulule la nuit",
  stormy: "Il y a de l'orage dehors",
  snowy: "La neige tombe doucement",
  tornado: "La tornade tourne très vite",
  windy: "Le vent souffle fort",
  foggy: "Le brouillard cache la route",
  lightning: "L'éclair brille dans le ciel",
  happy: "Je suis heureux aujourd'hui",
  sad: "Je me sens triste",
  angry: "Il est en colère",
  sleepy: "J'ai très sommeil",
  hug: "Je fais un gros câlin",
  clap: "Je tape dans mes mains",
  dance: "Je danse avec joie",
  flip: "Je fais une roulade",
  smile: "Je souris à mes amis",
  laugh: "Je ris très fort",
  think: "Je réfléchis calmement",
  celebrate: "Nous faisons la fête",
  wave: "Je fais coucou de la main",
  eye: "Je vois avec mes yeux",
  ear: "J'écoute avec mes oreilles",
  nose: "Je sens avec mon nez",
  mouth: "Je parle avec ma bouche",
  tongue: "Ma langue goûte la nourriture",
  hand: "Je tiens le crayon avec ma main",
  foot: "Je marche avec mon pied",
  leg: "Ma jambe peut sauter",
  tooth: "Une dent aide à mâcher",
  arm: "Je lève mon bras",
  brain: "Mon cerveau m'aide à penser",
  heart: "Mon cœur bat boum boum",
};
