export const FRENCH_SENTENCE_TEMPLATES: Record<string, string> = {
  // Fruits & Vegetables
  apple: "Je mange une pomme rouge",
  banana: "La banane est jaune et sucrée",
  grapes: "J'adore les raisins violets",
  strawberry: "La fraise est rouge et juteuse",
  carrot: "La carotte est croquante et orange",
  cucumber: "Le concombre est frais et vert",
  watermelon: "La pastèque est grande et juteuse",
  broccoli: "Je mange du brocoli sain",
  orange: "L'orange est ronde et juteuse",
  lemon: "Le citron est acide et jaune",
  peach: "La pêche est douce et sucrée",
  cherry: "La cerise est petite et rouge",
  kiwi: "Le kiwi est poilu et vert",

  // Counting (1-15)
  one: "Un",
  two: "Deux",
  three: "Trois",
  four: "Quatre",
  five: "Cinq",
  six: "Six",
  seven: "Sept",
  eight: "Huit",
  nine: "Neuf",
  ten: "Dix",

  // Shapes & Colors
  circle: "Le cercle est rond",
  triangle: "Le triangle a trois côtés",
  star: "L'étoile brille",
  blue: "Le ciel est bleu",
  red: "La pomme est rouge",
  green: "L'herbe est verte",
  purple: "Les raisins sont violets",
  yellow: "Le soleil est jaune",

  // Animals & Nature
  dog: "Le chien fait wouf",
  cat: "Le chat fait miaou",
  fox: "Le renard est intelligent",
  turtle: "La tortue se déplace lentement",
  butterfly: "Le papillon est beau",
  tree: "L'arbre est grand",
  flower: "La fleur est jolie",
  elephant: "L'éléphant est grand",
  lion: "Le lion rugit",
  rabbit: "Le lapin saute",
  giraffe: "La girafe a un long cou",
  penguin: "Le pingouin se dandine sur la glace",

  // Things That Go
  car: "La voiture roule sur la route",
  bus: "Le bus jaune nous emmène à l'école",
  "fire truck": "Le camion de pompiers a une sirène forte",
  airplane: "L'avion vole dans le ciel",
  rocket: "La fusée va dans l'espace",
  bicycle: "Je fais du vélo au parc",
  helicopter: "L'hélicoptère monte et descend",
  boat: "Le bateau flotte sur l'eau",
  train: "Le train roule sur les rails",
  taxi: "Le taxi transporte les gens",
  van: "Le van transporte notre famille",
  scooter: "Je roule vite sur ma trottinette",
  motorcycle: "La moto fait vroum",

  // Weather
  sunny: "Il fait beau aujourd'hui",
  cloudy: "Le ciel est nuageux",
  rainy: "Il pleut dehors",
  rainbow: "Je vois un bel arc-en-ciel",
  moon: "La lune brille la nuit",
  sun: "Le soleil nous donne de la lumière",

  // Alphabet
  a: "A comme Avion",
  b: "B comme Ballon",
  c: "C comme Chat",
  d: "D comme Dauphin",
  e: "E comme Éléphant",
  f: "F comme Fleur",
  g: "G comme Girafe",
  h: "H comme Hélicoptère",
  i: "I comme Igloo",
  j: "J comme Jus",
  k: "K comme Koala",
  l: "L comme Lion",
  m: "M comme Maison",
  n: "N comme Nid",
  o: "O comme Orange",
  p: "P comme Pingouin",
  q: "Q comme Quatre",
  r: "R comme Arc-en-ciel",
  s: "S comme Soleil",
  t: "T comme Tortue",
  u: "U comme Ours",
  v: "V comme Van",
  w: "W comme Wagon",
  x: "X comme Xylophone",
  y: "Y comme Yaourt",
  z: "Z comme Zèbre",
};
