export const MANDARIN_GAMEPLAY_COMPLETION_TEMPLATES: Record<string, string> = {
  cucumber: "黄瓜是绿色的，很清脆。",
  broccoli: "西兰花是绿色的，很健康。",
  lemon: "柠檬酸酸的，是黄色的。",
  peach: "桃子软软的，很香甜。",
  cherry: "樱桃小小的，红红的。",
  kiwi: "猕猴桃里面是绿色的。",
  purple: "葡萄是紫色的。",
  white: "云朵是白色的。",
  brown: "小熊是棕色的。",
  black: "夜空是黑色的。",
  diamond: "菱形有四条边。",
  fox: "狐狸跑得很快。",
  owl: "猫头鹰晚上醒着。",
  lion: "狮子大声吼叫。",
  rabbit: "兔子蹦蹦跳跳。",
  giraffe: "长颈鹿的脖子很长。",
  "fire truck": "消防车开着响亮的警报。",
  helicopter: "直升机在天空中盘旋。",
  boat: "小船在水上漂。",
  taxi: "出租车载着人们出发。",
  van: "面包车能坐很多人。",
  scooter: "滑板车滑得很快。",
  motorcycle: "摩托车轰隆隆地开。",
  stormy: "外面刮风打雷，有暴风雨。",
  snowy: "雪花轻轻地落下来。",
  tornado: "龙卷风转得很快。",
  windy: "风吹得很大。",
  foggy: "有雾的时候看不太清。",
  lightning: "闪电在天空中发亮。",
  happy: "我开心地笑了。",
  sad: "我难过的时候想抱抱。",
  angry: "生气的时候要深呼吸。",
  sleepy: "我困了，想睡觉。",
  hug: "我给朋友一个大大的拥抱。",
  clap: "我们一起拍拍手。",
  dance: "我跟着音乐跳舞。",
  flip: "我做了一个前滚翻。",
  smile: "我对大家微笑。",
  laugh: "我哈哈大笑。",
  think: "我安静地想一想。",
  celebrate: "我们一起庆祝成功。",
  wave: "我挥手说你好。",
  eye: "我用眼睛看东西。",
  ear: "我用耳朵听声音。",
  nose: "我用鼻子闻气味。",
  mouth: "我用嘴巴说话。",
  tongue: "我用舌头尝味道。",
  hand: "我用手拿蜡笔。",
  foot: "我用脚走路。",
  leg: "我的腿可以跳起来。",
  tooth: "牙齿帮助我咀嚼。",
  arm: "我举起手臂打招呼。",
  brain: "大脑帮助我思考。",
  heart: "心脏扑通扑通地跳。",
  f: "F 是字母 F。",
  g: "G 是字母 G。",
  h: "H 是字母 H。",
  i: "I 是字母 I。",
  j: "J 是字母 J。",
  k: "K 是字母 K。",
  l: "L 是字母 L。",
  m: "M 是字母 M。",
  n: "N 是字母 N。",
  o: "O 是字母 O。",
  p: "P 是字母 P。",
  q: "Q 是字母 Q。",
  r: "R 是字母 R。",
  s: "S 是字母 S。",
  t: "T 是字母 T。",
  u: "U 是字母 U。",
  v: "V 是字母 V。",
  w: "W 是字母 W。",
  x: "X 是字母 X。",
  y: "Y 是字母 Y。",
  z: "Z 是字母 Z。",
};
