export const CANTONESE_GAMEPLAY_COMPLETION_TEMPLATES: Record<string, string> = {
  cucumber: "青瓜係綠色又好爽脆。",
  broccoli: "西蘭花係綠色又有益。",
  lemon: "檸檬酸酸哋又係黃色。",
  peach: "桃又軟又甜。",
  cherry: "車厘子細細粒又紅卜卜。",
  kiwi: "奇異果入面係綠色。",
  purple: "提子係紫色。",
  white: "雲係白色。",
  brown: "小熊係啡色。",
  black: "夜空係黑色。",
  diamond: "菱形有四條邊。",
  fox: "狐狸跑得好快。",
  owl: "貓頭鷹夜晚先醒。",
  lion: "獅子大聲吼叫。",
  rabbit: "兔仔跳嚟跳去。",
  giraffe: "長頸鹿條頸好長。",
  "fire truck": "消防車響住警號出動。",
  helicopter: "直升機喺天空盤旋。",
  boat: "小船喺水面漂浮。",
  taxi: "的士載住乘客出發。",
  van: "客貨車可以載好多人。",
  scooter: "滑板車滑得好快。",
  motorcycle: "電單車轟轟聲咁行。",
  stormy: "出面打風又行雷。",
  snowy: "雪花輕輕咁落低。",
  tornado: "龍捲風轉得好快。",
  windy: "風大大力咁吹。",
  foggy: "有霧嘅時候睇唔清。",
  lightning: "閃電喺天空發光。",
  happy: "我開心到笑晒。",
  sad: "我唔開心想要抱抱。",
  angry: "我嬲嘅時候會深呼吸。",
  sleepy: "我眼瞓想瞓覺。",
  hug: "我畀朋友一個大擁抱。",
  clap: "我哋一齊拍手。",
  dance: "我跟住音樂跳舞。",
  flip: "我做咗一個前滾翻。",
  smile: "我笑住同大家打招呼。",
  laugh: "我哈哈大笑。",
  think: "我靜靜哋諗一諗。",
  celebrate: "我哋一齊慶祝成功。",
  wave: "我揮手講你好。",
  eye: "我用眼睛睇嘢。",
  ear: "我用耳仔聽聲。",
  nose: "我用鼻聞氣味。",
  mouth: "我用口講嘢。",
  tongue: "我用脷嚟試味。",
  hand: "我用手拎蠟筆。",
  foot: "我用腳行路。",
  leg: "我隻腳可以跳高。",
  tooth: "牙齒幫我咬食物。",
  arm: "我舉高手臂打招呼。",
  brain: "大腦幫我思考。",
  heart: "心口入面個心撲通撲通跳。",
  f: "F 係字母 F。",
  g: "G 係字母 G。",
  h: "H 係字母 H。",
  i: "I 係字母 I。",
  j: "J 係字母 J。",
  k: "K 係字母 K。",
  l: "L 係字母 L。",
  m: "M 係字母 M。",
  n: "N 係字母 N。",
  o: "O 係字母 O。",
  p: "P 係字母 P。",
  q: "Q 係字母 Q。",
  r: "R 係字母 R。",
  s: "S 係字母 S。",
  t: "T 係字母 T。",
  u: "U 係字母 U。",
  v: "V 係字母 V。",
  w: "W 係字母 W。",
  x: "X 係字母 X。",
  y: "Y 係字母 Y。",
  z: "Z 係字母 Z。",
};
