/**
 * Phonics sound mapping for educational pronunciation
 * Maps words to their phonetic breakdown for teaching
 * Example: "apple" → ["Aah", "Aah", "Apple"]
 */
export const PHONICS_MAP: Record<string, string[]> = {
    // Fruits & Vegetables
    'apple': ['Aah', 'Aah', 'Apple'],
    'banana': ['Buh', 'Buh', 'Banana'],
    'grapes': ['Guh', 'Guh', 'Grapes'],
    'strawberry': ['Sss', 'Sss', 'Strawberry'],
    'carrot': ['Kuh', 'Kuh', 'Carrot'],
    'cucumber': ['Kuh', 'Kuh', 'Cucumber'],
    'watermelon': ['Wuh', 'Wuh', 'Watermelon'],
    'broccoli': ['Buh', 'Buh', 'Broccoli'],
    'orange': ['Ooh', 'Ooh', 'Orange'],
    'lemon': ['Lll', 'Lll', 'Lemon'],
    'peach': ['Puh', 'Puh', 'Peach'],
    'cherry': ['Chh', 'Chh', 'Cherry'],
    'kiwi': ['Kuh', 'Kuh', 'Kiwi'],

    // Numbers
    'one': ['Wuh', 'Wuh', 'One'],
    '1': ['Wuh', 'Wuh', 'One'],
    'two': ['Tuh', 'Tuh', 'Two'],
    '2': ['Tuh', 'Tuh', 'Two'],
    'three': ['Thh', 'Thh', 'Three'],
    '3': ['Thh', 'Thh', 'Three'],
    'four': ['Fff', 'Fff', 'Four'],
    '4': ['Fff', 'Fff', 'Four'],
    'five': ['Fff', 'Fff', 'Five'],
    '5': ['Fff', 'Fff', 'Five'],
    'six': ['Sss', 'Sss', 'Six'],
    '6': ['Sss', 'Sss', 'Six'],
    'seven': ['Sss', 'Sss', 'Seven'],
    '7': ['Sss', 'Sss', 'Seven'],
    'eight': ['Eee', 'Eee', 'Eight'],
    '8': ['Eee', 'Eee', 'Eight'],
    'nine': ['Nnn', 'Nnn', 'Nine'],
    '9': ['Nnn', 'Nnn', 'Nine'],
    'ten': ['Tuh', 'Tuh', 'Ten'],
    '10': ['Tuh', 'Tuh', 'Ten'],
    'eleven': ['Eee', 'Eee', 'Eleven'],
    '11': ['Eee', 'Eee', 'Eleven'],
    'twelve': ['Tuh', 'Tuh', 'Twelve'],
    '12': ['Tuh', 'Tuh', 'Twelve'],
    'thirteen': ['Thh', 'Thh', 'Thirteen'],
    '13': ['Thh', 'Thh', 'Thirteen'],
    'fourteen': ['Fff', 'Fff', 'Fourteen'],
    '14': ['Fff', 'Fff', 'Fourteen'],
    'fifteen': ['Fff', 'Fff', 'Fifteen'],
    '15': ['Fff', 'Fff', 'Fifteen'],

    // Shapes & Colors
    'blue': ['Buh', 'Buh', 'Blue'],
    'red': ['Rrr', 'Rrr', 'Red'],
    'green': ['Guh', 'Guh', 'Green'],
    'yellow': ['Yyy', 'Yyy', 'Yellow'],
    'brown': ['Buh', 'Buh', 'Brown'],
    'black': ['Buh', 'Buh', 'Black'],
    'purple': ['Puh', 'Puh', 'Purple'],
    'white': ['Wuh', 'Wuh', 'White'],
    'triangle': ['Tuh', 'Tuh', 'Triangle'],
    'star': ['Sss', 'Sss', 'Star'],
    'diamond': ['Ddd', 'Ddd', 'Diamond'],
    'circle': ['Sss', 'Sss', 'Circle'],

    // Animals & Nature
    'dog': ['Ddd', 'Ddd', 'Dog'],
    'cat': ['Kuh', 'Kuh', 'Cat'],
    'fox': ['Fff', 'Fff', 'Fox'],
    'turtle': ['Tuh', 'Tuh', 'Turtle'],
    'butterfly': ['Buh', 'Buh', 'Butterfly'],
    'owl': ['Ooo', 'Ooo', 'Owl'],
    'tree': ['Tuh', 'Tuh', 'Tree'],
    'flower': ['Fff', 'Fff', 'Flower'],
    'elephant': ['Eee', 'Eee', 'Elephant'],
    'lion': ['Lll', 'Lll', 'Lion'],
    'rabbit': ['Rrr', 'Rrr', 'Rabbit'],
    'giraffe': ['Jjj', 'Jjj', 'Giraffe'],
    'penguin': ['Puh', 'Puh', 'Penguin'],

    // Things That Go
    'car': ['Kuh', 'Kuh', 'Car'],
    'bus': ['Buh', 'Buh', 'Bus'],
    'fire truck': ['Fff', 'Fff', 'Fire Truck'],
    'airplane': ['Aah', 'Aah', 'Airplane'],
    'rocket': ['Rrr', 'Rrr', 'Rocket'],
    'bicycle': ['Buh', 'Buh', 'Bicycle'],
    'helicopter': ['Hhh', 'Hhh', 'Helicopter'],
    'boat': ['Buh', 'Buh', 'Boat'],
    'train': ['Tuh', 'Tuh', 'Train'],
    'taxi': ['Tuh', 'Tuh', 'Taxi'],
    'van': ['Vvv', 'Vvv', 'Van'],
    'scooter': ['Sss', 'Sss', 'Scooter'],
    'motorcycle': ['Mmm', 'Mmm', 'Motorcycle'],

    // Weather Wonders
    'sunny': ['Sss', 'Sss', 'Sunny'],
    'cloudy': ['Kuh', 'Kuh', 'Cloudy'],
    'rainy': ['Rrr', 'Rrr', 'Rainy'],
    'stormy': ['Sss', 'Sss', 'Stormy'],
    'snowy': ['Sss', 'Sss', 'Snowy'],
    'rainbow': ['Rrr', 'Rrr', 'Rainbow'],
    'tornado': ['Tuh', 'Tuh', 'Tornado'],
    'windy': ['Wuh', 'Wuh', 'Windy'],
    'moon': ['Mmm', 'Mmm', 'Moon'],
    'sun': ['Sss', 'Sss', 'Sun'],
    'foggy': ['Fff', 'Fff', 'Foggy'],
    'lightning': ['Lll', 'Lll', 'Lightning'],

    // Feelings & Actions
    'happy': ['Hhh', 'Hhh', 'Happy'],
    'sad': ['Sss', 'Sss', 'Sad'],
    'angry': ['Aah', 'Aah', 'Angry'],
    'sleepy': ['Sss', 'Sss', 'Sleepy'],
    'hug': ['Hhh', 'Hhh', 'Hug'],
    'clap': ['Kuh', 'Kuh', 'Clap'],
    'dance': ['Ddd', 'Ddd', 'Dance'],
    'flip': ['Fff', 'Fff', 'Flip'],
    'smile': ['Sss', 'Sss', 'Smile'],
    'laugh': ['Lll', 'Lll', 'Laugh'],
    'think': ['Thh', 'Thh', 'Think'],
    'celebrate': ['Sss', 'Sss', 'Celebrate'],
    'wave': ['Wuh', 'Wuh', 'Wave'],

    // Body Parts
    'eye': ['Ahy', 'Ahy', 'Eye'],
    'ear': ['Eee', 'Eee', 'Ear'],
    'nose': ['Nnn', 'Nnn', 'Nose'],
    'mouth': ['Mmm', 'Mmm', 'Mouth'],
    'tongue': ['Tuh', 'Tuh', 'Tongue'],
    'hand': ['Hhh', 'Hhh', 'Hand'],
    'foot': ['Fff', 'Fff', 'Foot'],
    'leg': ['Lll', 'Lll', 'Leg'],
    'tooth': ['Tuh', 'Tuh', 'Tooth'],
    'arm': ['Aah', 'Aah', 'Arm'],
    'brain': ['Buh', 'Buh', 'Brain'],
    'heart': ['Hhh', 'Hhh', 'Heart'],

    // Alphabet (letters use phonetic sounds)
    'A': ['Aah', 'Aah', 'A'],
    'B': ['Buh', 'Buh', 'B'],
    'C': ['Kuh', 'Kuh', 'C'],
    'D': ['Ddd', 'Ddd', 'D'],
    'E': ['Eee', 'Eee', 'E'],
    'F': ['Fff', 'Fff', 'F'],
    'G': ['Guh', 'Guh', 'G'],
    'H': ['Hhh', 'Hhh', 'H'],
    'I': ['Iii', 'Iii', 'I'],
    'J': ['Jjj', 'Jjj', 'J'],
    'K': ['Kuh', 'Kuh', 'K'],
    'L': ['Lll', 'Lll', 'L'],
    'M': ['Mmm', 'Mmm', 'M'],
    'N': ['Nnn', 'Nnn', 'N'],
    'O': ['Ooo', 'Ooo', 'O'],
    'P': ['Puh', 'Puh', 'P'],
    'Q': ['Kuh', 'Kuh', 'Q'],
    'R': ['Rrr', 'Rrr', 'R'],
    'S': ['Sss', 'Sss', 'S'],
    'T': ['Tuh', 'Tuh', 'T'],
    'U': ['Uuu', 'Uuu', 'U'],
    'V': ['Vvv', 'Vvv', 'V'],
    'W': ['Wuh', 'Wuh', 'W'],
    'X': ['Eks', 'Eks', 'X'],
    'Y': ['Yyy', 'Yyy', 'Y'],
    'Z': ['Zzz', 'Zzz', 'Z'],
}

/**
 * Get phonics pronunciation for a word
 * Returns array of [phonicSound, phonicSound, fullWord]
 */
export function getPhonics(word: string): string[] | null {
    const normalized = word.toLowerCase().trim()
    return PHONICS_MAP[normalized] || null
}
