import type { SupportedLanguage } from "./language-config";

const THAI_TARGET_LABELS: Record<string, string> = {
  apple: "แอปเปิ้ล",
  banana: "กล้วย",
  grapes: "องุ่น",
  strawberry: "สตรอเบอร์รี่",
  carrot: "แครอท",
  cucumber: "แตงกวา",
  watermelon: "แตงโม",
  broccoli: "บรอกโคลี",
  orange: "ส้ม",
  lemon: "มะนาว",
  peach: "ลูกพีช",
  cherry: "เชอร์รี",
  kiwi: "กีวี",
  one: "หนึ่ง",
  two: "สอง",
  three: "สาม",
  four: "สี่",
  five: "ห้า",
  six: "หก",
  seven: "เจ็ด",
  eight: "แปด",
  nine: "เก้า",
  ten: "สิบ",
  circle: "วงกลม",
  diamond: "สี่เหลี่ยมข้าวหลามตัด",
  triangle: "สามเหลี่ยม",
  star: "ดาว",
  blue: "สีน้ำเงิน",
  red: "สีแดง",
  green: "สีเขียว",
  purple: "สีม่วง",
  white: "สีขาว",
  black: "สีดำ",
  brown: "สีน้ำตาล",
  yellow: "สีเหลือง",
  dog: "สุนัข",
  cat: "แมว",
  fox: "สุนัขจิ้งจอก",
  turtle: "เต่า",
  butterfly: "ผีเสื้อ",
  owl: "นกฮูก",
  tree: "ต้นไม้",
  flower: "ดอกไม้",
  elephant: "ช้าง",
  lion: "สิงโต",
  rabbit: "กระต่าย",
  giraffe: "ยีราฟ",
  penguin: "เพนกวิน",
  car: "รถยนต์",
  bus: "รถบัส",
  "fire truck": "รถดับเพลิง",
  airplane: "เครื่องบิน",
  rocket: "จรวด",
  bicycle: "จักรยาน",
  helicopter: "เฮลิคอปเตอร์",
  boat: "เรือ",
  train: "รถไฟ",
  taxi: "แท็กซี่",
  van: "รถตู้",
  scooter: "สกู๊ตเตอร์",
  motorcycle: "มอเตอร์ไซค์",
  sunny: "แดดออก",
  cloudy: "มีเมฆมาก",
  rainy: "ฝนตก",
  stormy: "พายุ",
  snowy: "หิมะตก",
  rainbow: "รุ้ง",
  tornado: "พายุทอร์นาโด",
  windy: "ลมแรง",
  moon: "ดวงจันทร์",
  sun: "ดวงอาทิตย์",
  foggy: "มีหมอก",
  lightning: "สายฟ้า",
  happy: "มีความสุข",
  sad: "เศร้า",
  angry: "โกรธ",
  sleepy: "ง่วงนอน",
  hug: "กอด",
  clap: "ปรบมือ",
  dance: "เต้น",
  flip: "ตีลังกา",
  smile: "ยิ้ม",
  laugh: "หัวเราะ",
  think: "คิด",
  celebrate: "ฉลอง",
  wave: "โบกมือ",
  eye: "ตา",
  ear: "หู",
  nose: "จมูก",
  mouth: "ปาก",
  tongue: "ลิ้น",
  hand: "มือ",
  foot: "เท้า",
  leg: "ขา",
  tooth: "ฟัน",
  arm: "แขน",
  brain: "สมอง",
  heart: "หัวใจ",
  a: "เอ",
  b: "บี",
  c: "ซี",
  d: "ดี",
  e: "อี",
  f: "เอฟ",
  g: "จี",
  h: "เอช",
  i: "ไอ",
  j: "เจ",
  k: "เค",
  l: "แอล",
  m: "เอ็ม",
  n: "เอ็น",
  o: "โอ",
  p: "พี",
  q: "คิว",
  r: "อาร์",
  s: "เอส",
  t: "ที",
  u: "ยู",
  v: "วี",
  w: "ดับเบิลยู",
  x: "เอ็กซ์",
  y: "วาย",
  z: "แซด",
};

export const getTargetDisplayLabel = (
  targetName: string,
  language: SupportedLanguage,
  categoryName?: string,
) => {
  const normalizedTarget = targetName.toLowerCase().trim();
  if (language !== "th") {
    return targetName;
  }
  if (normalizedTarget === "orange" && categoryName === "Shapes & Colors") {
    return "สีส้ม";
  }
  return THAI_TARGET_LABELS[normalizedTarget] ?? targetName;
};

export { THAI_TARGET_LABELS };
